Radium.BulkActionProperties = Ember.Mixin.create
  ids: DS.attr('array')
  user: DS.belongsTo('Radium.User')
  list: DS.belongsTo('Radium.List')
  public: DS.attr('boolean')
  private: DS.attr('boolean')
  newTags: DS.attr('array')
  filter: DS.attr('string')
  like: DS.attr('string')
  customquery: DS.attr('string')
