Radium.Countries = [
  {key: 'US', 'label':'United States','currencyflag':''}
  {key: 'GB', 'label':'United Kingdom','currencyflag':''},
  {key: 'AF', 'label':'Afghanistan','currencyflag':''},
  {key: 'AL', 'label':'Albania','currencyflag':''},
  {key: 'DZ', 'label':'Algeria','currencyflag':''},
  {key: 'AS', 'label':'American Samoa','currencyflag':''},
  {key: 'AD', 'label':'Andorra','currencyflag':''},
  {key: 'AI', 'label':'Anguilla','currencyflag':''},
  {key: 'AQ', 'label':'Antarctica','currencyflag':''},
  {key: 'AG', 'label':'Antigua and Barbuda','currencyflag':''},
  {key: 'AO', 'label':'Angola','currencyflag':''},
  {key: 'AR', 'label':'Argentina','currencyflag':''},
  {key: 'AM', 'label':'Armenia','currencyflag':''},
  {key: 'AW', 'label':'Aruba','currencyflag':''},
  {key: 'AU', 'label':'Australia','currencyflag':'AUD'},
  {key: 'AT', 'label':'Austria','currencyflag':''},
  {key: 'AZ', 'label':'Azerbaijan','currencyflag':''},
  {key: 'BH', 'label':'Bahrain','currencyflag':''},
  {key: 'BD', 'label':'Bangladesh','currencyflag':''},
  {key: 'BB', 'label':'Barbados','currencyflag':''},
  {key: 'BY', 'label':'Belarus','currencyflag':''},
  {key: 'BE', 'label':'Belgium','currencyflag':''},
  {key: 'BZ', 'label':'Belize','currencyflag':''},
  {key: 'BJ', 'label':'Benin','currencyflag':''},
  {key: 'BM', 'label':'Bermuda','currencyflag':''},
  {key: 'BT', 'label':'Bhutan','currencyflag':''},
  {key: 'BO', 'label':'Bolivia','currencyflag':''},
  {key: 'BA', 'label':'Bosnia and Herzegovina','currencyflag':''},
  {key: 'BW', 'label':'Botswana','currencyflag':''},
  {key: 'BV', 'label':'Bouvet Island','currencyflag':''},
  {key: 'BR', 'label':'Brazil','currencyflag':''},
  {key: 'IO', 'label':'British Indian Ocean Territory','currencyflag':''},
  {key: 'VG', 'label':'British Virgin Islands','currencyflag':''},
  {key: 'BN', 'label':'Brunei','currencyflag':''},
  {key: 'BG', 'label':'Bulgaria','currencyflag':''},
  {key: 'BF', 'label':'Burkina Faso','currencyflag':''},
  {key: 'BI', 'label':'Burundi','currencyflag':''},
  {key: 'CI', 'label':'Côte d\'Ivoire','currencyflag':''},
  {key: 'KH', 'label':'Cambodia','currencyflag':''},
  {key: 'CM', 'label':'Cameroon','currencyflag':''},
  {key: 'CA', 'label':'Canada','currencyflag':''},
  {key: 'CV', 'label':'Cape Verde','currencyflag':''},
  {key: 'KY', 'label':'Cayman Islands','currencyflag':''},
  {key: 'CF', 'label':'Central African Republic','currencyflag':''},
  {key: 'TD', 'label':'Chad','currencyflag':''},
  {key: 'CL', 'label':'Chilea','currencyflag':''},
  {key: 'CN', 'label':'China','currencyflag':''},
  {key: 'CX', 'label':'Christmas Island','currencyflag':''},
  {key: 'CC', 'label':'Cocos (Keeling) Islands','currencyflag':''},
  {key: 'CO', 'label':'Colombia','currencyflag':''},
  {key: 'KM', 'label':'Comoros','currencyflag':''},
  {key: 'CG', 'label':'Congo','currencyflag':''},
  {key: 'CK', 'label':'Cook Islands','currencyflag':''},
  {key: 'CR', 'label':'Costa Rica','currencyflag':''},
  {key: 'HR', 'label':'Croatia','currencyflag':''},
  {key: 'CU', 'label':'Cuba','currencyflag':''},
  {key: 'CY', 'label':'Cyprus','currencyflag':''},
  {key: 'CZ', 'label':'Czech Republic','currencyflag':''},
  {key: 'CD', 'label':'Democratic Republic of the Congo','currencyflag':''},
  {key: 'DK', 'label':'Denmark','currencyflag':'DKK'},
  {key: 'DJ', 'label':'Djibouti','currencyflag':''},
  {key: 'DM', 'label':'Dominica','currencyflag':''},
  {key: 'DO', 'label':'Dominican Republic','currencyflag':''},
  {key: 'TP', 'label':'East Timor','currencyflag':''},
  {key: 'EC', 'label':'Ecuador','currencyflag':''},
  {key: 'EG', 'label':'Egypt','currencyflag':''},
  {key: 'SV', 'label':'El Salvador','currencyflag':''},
  {key: 'GQ', 'label':'Equatorial Guinea','currencyflag':''},
  {key: 'ER', 'label':'Eritrea','currencyflag':''},
  {key: 'EE', 'label':'Estonia','currencyflag':''},
  {key: 'ET', 'label':'Ethiopia','currencyflag':''},
  {key: 'FO', 'label':'Faeroe Islands','currencyflag':''},
  {key: 'FK', 'label':'Falkland Islands','currencyflag':''},
  {key: 'FJ', 'label':'Fiji','currencyflag':''},
  {key: 'FI', 'label':'Finland','currencyflag':''},
  {key: 'MK', 'label':'Former Yugoslav Republic of Macedonia','currencyflag':''},
  {key: 'FR', 'label':'France','currencyflag':''},
  {key: 'FX', 'label':'France, Metropolitan','currencyflag':''},
  {key: 'GF', 'label':'French Guiana','currencyflag':''},
  {key: 'PF', 'label':'French Polynesia','currencyflag':''},
  {key: 'TF', 'label':'French Southern Territories','currencyflag':''},
  {key: 'GA', 'label':'Gabon','currencyflag':''},
  {key: 'GE', 'label':'Georgia','currencyflag':''},
  {key: 'DE', 'label':'Germany','currencyflag':''},
  {key: 'GH', 'label':'Ghana','currencyflag':''},
  {key: 'GI', 'label':'Gibraltar','currencyflag':''},
  {key: 'GR', 'label':'Greece','currencyflag':''},
  {key: 'GL', 'label':'Greenland','currencyflag':''},
  {key: 'GD', 'label':'Grenada','currencyflag':''},
  {key: 'GP', 'label':'Guadeloupe','currencyflag':''},
  {key: 'GU', 'label':'Guam','currencyflag':''},
  {key: 'GT', 'label':'Guatemala','currencyflag':''},
  {key: 'GN', 'label':'Guinea','currencyflag':''},
  {key: 'GW', 'label':'Guinea-Bissau','currencyflag':''},
  {key: 'GY', 'label':'Guyana','currencyflag':''},
  {key: 'HT', 'label':'Haiti','currencyflag':''},
  {key: 'HM', 'label':'Heard and Mc Donald Islands','currencyflag':''},
  {key: 'HN', 'label':'Honduras','currencyflag':''},
  {key: 'HK', 'label':'Hong Kong','currencyflag':''},
  {key: 'HU', 'label':'Hungary','currencyflag':''},
  {key: 'IS', 'label':'Iceland','currencyflag':''},
  {key: 'IN', 'label':'India','currencyflag':''},
  {key: 'ID', 'label':'Indonesia','currencyflag':''},
  {key: 'IR', 'label':'Iran','currencyflag':''},
  {key: 'IQ', 'label':'Iraq','currencyflag':''},
  {key: 'IE', 'label':'Ireland','currencyflag':''},
  {key: 'IL', 'label':'Israel','currencyflag':''},
  {key: 'IT', 'label':'Italy','currencyflag':''},
  {key: 'JM', 'label':'Jamaica','currencyflag':''},
  {key: 'JP', 'label':'Japan','currencyflag':''},
  {key: 'JO', 'label':'Jordan','currencyflag':''},
  {key: 'KZ', 'label':'Kazakhstan','currencyflag':''},
  {key: 'KE', 'label':'Kenya','currencyflag':''},
  {key: 'KI', 'label':'Kiribati','currencyflag':''},
  {key: 'KW', 'label':'Kuwait','currencyflag':''},
  {key: 'KG', 'label':'Kyrgyzstan','currencyflag':''},
  {key: 'LA', 'label':'Laos','currencyflag':''},
  {key: 'LV', 'label':'Latvia','currencyflag':''},
  {key: 'LB', 'label':'Lebanon','currencyflag':''},
  {key: 'LS', 'label':'Lesotho','currencyflag':''},
  {key: 'LR', 'label':'Liberia','currencyflag':''},
  {key: 'LY', 'label':'Libya','currencyflag':''},
  {key: 'LI', 'label':'Liechtenstein','currencyflag':''},
  {key: 'LT', 'label':'Lithuania','currencyflag':''},
  {key: 'LU', 'label':'Luxembourg','currencyflag':''},
  {key: 'MO', 'label':'Macau','currencyflag':''},
  {key: 'MG', 'label':'Madagascar','currencyflag':''},
  {key: 'MW', 'label':'Malawi','currencyflag':''},
  {key: 'MY', 'label':'Malaysia','currencyflag':''},
  {key: 'MV', 'label':'Maldives','currencyflag':''},
  {key: 'ML', 'label':'Mali','currencyflag':''},
  {key: 'MT', 'label':'Malta','currencyflag':''},
  {key: 'MH', 'label':'Marshall Islands','currencyflag':''},
  {key: 'MQ', 'label':'Martinique','currencyflag':''},
  {key: 'MR', 'label':'Mauritania','currencyflag':''},
  {key: 'MU', 'label':'Mauritius','currencyflag':''},
  {key: 'YT', 'label':'Mayotte','currencyflag':''},
  {key: 'MX', 'label':'Mexico','currencyflag':''},
  {key: 'FM', 'label':'Micronesia','currencyflag':''},
  {key: 'MD', 'label':'Moldova','currencyflag':''},
  {key: 'MC', 'label':'Monaco','currencyflag':''},
  {key: 'MN', 'label':'Mongolia','currencyflag':''},
  {key: 'ME', 'label':'Montenegro','currencyflag':''},
  {key: 'MS', 'label':'Montserrat','currencyflag':''},
  {key: 'MA', 'label':'Morocco','currencyflag':''},
  {key: 'MZ', 'label':'Mozambique','currencyflag':''},
  {key: 'MM', 'label':'Myanmar','currencyflag':''},
  {key: 'NA', 'label':'Namibia','currencyflag':''},
  {key: 'NR', 'label':'Nauru','currencyflag':''},
  {key: 'NP', 'label':'Nepal','currencyflag':''},
  {key: 'NL', 'label':'Netherlands','currencyflag':''},
  {key: 'AN', 'label':'Netherlands Antilles','currencyflag':''},
  {key: 'NC', 'label':'New Caledonia','currencyflag':''},
  {key: 'NZ', 'label':'New Zealand','currencyflag':''},
  {key: 'NI', 'label':'Nicaragua','currencyflag':''},
  {key: 'NE', 'label':'Niger','currencyflag':''},
  {key: 'NG', 'label':'Nigeria','currencyflag':''},
  {key: 'NU', 'label':'Niue','currencyflag':''},
  {key: 'NF', 'label':'Norfolk Islan','currencyflag':''},
  {key: 'KP', 'label':'North Korea','currencyflag':''},
  {key: 'MP', 'label':'Northern Marianas','currencyflag':''},
  {key: 'NO', 'label':'Norway','currencyflag':''},
  {key: 'OM', 'label':'Oman','currencyflag':''},
  {key: 'PK', 'label':'Pakistan','currencyflag':''},
  {key: 'PW', 'label':'Palau','currencyflag':''},
  {key: 'PS', 'label':'Palestine','currencyflag':''},
  {key: 'PA', 'label':'Panama','currencyflag':''},
  {key: 'PG', 'label':'Papua New Guinea','currencyflag':''},
  {key: 'PY', 'label':'Paraguay','currencyflag':''},
  {key: 'PE', 'label':'Peru','currencyflag':''},
  {key: 'PH', 'label':'Philippines','currencyflag':''},
  {key: 'PN', 'label':'Pitcairn Islands','currencyflag':''},
  {key: 'PL', 'label':'Poland','currencyflag':''},
  {key: 'PT', 'label':'Portugal','currencyflag':''},
  {key: 'PR', 'label':'Puerto Rico','currencyflag':''},
  {key: 'QA', 'label':'Qatar','currencyflag':''},
  {key: 'RE', 'label':'Reunion','currencyflag':''},
  {key: 'RO', 'label':'Romania','currencyflag':''},
  {key: 'RU', 'label':'Russia','currencyflag':''},
  {key: 'RW', 'label':'Rwanda','currencyflag':''},
  {key: 'ST', 'label':'São Tomé and Príncipe','currencyflag':''},
  {key: 'SH', 'label':'Saint Helena','currencyflag':''},
  {key: 'PM', 'label':'St. Pierre and Miquelon','currencyflag':''},
  {key: 'KN', 'label':'Saint Kitts and Nevis','currencyflag':''},
  {key: 'LC', 'label':'Saint Lucia','currencyflag':''},
  {key: 'VC', 'label':'Saint Vincent and the Grenadines','currencyflag':''},
  {key: 'WS', 'label':'Samoa','currencyflag':''},
  {key: 'SM', 'label':'San Marino','currencyflag':''},
  {key: 'SA', 'label':'Saudi Arabia','currencyflag':''},
  {key: 'SN', 'label':'Senegal','currencyflag':''},
  {key: 'RS', 'label':'Serbia','currencyflag':''},
  {key: 'SC', 'label':'Seychelles','currencyflag':''},
  {key: 'SL', 'label':'Sierra Leone','currencyflag':''},
  {key: 'SG', 'label':'Singapore','currencyflag':''},
  {key: 'SK', 'label':'Slovakia','currencyflag':''},
  {key: 'SI', 'label':'Slovenia','currencyflag':''},
  {key: 'SB', 'label':'Solomon Islands','currencyflag':''},
  {key: 'SO', 'label':'Somalia','currencyflag':''},
  {key: 'ZA', 'label':'South Africa','currencyflag':''},
  {key: 'GS', 'label':'South Georgia and the South Sandwich Islands','currencyflag':''},
  {key: 'KR', 'label':'South Korea','currencyflag':''},
  {key: 'ES', 'label':'Spain','currencyflag':''},
  {key: 'LK', 'label':'Sri Lanka','currencyflag':''},
  {key: 'SD', 'label':'Sudan','currencyflag':''},
  {key: 'SR', 'label':'Suriname','currencyflag':''},
  {key: 'SJ', 'label':'Svalbard and Jan Mayen Islands','currencyflag':''},
  {key: 'SZ', 'label':'Swaziland','currencyflag':''},
  {key: 'SE', 'label':'Sweden','currencyflag':''},
  {key: 'CH', 'label':'Switzerland','currencyflag':'CHF'},
  {key: 'SY', 'label':'Syria','currencyflag':''},
  {key: 'TW', 'label':'Taiwan','currencyflag':''},
  {key: 'TJ', 'label':'Tajikistan','currencyflag':''},
  {key: 'TZ', 'label':'Tanzania','currencyflag':''},
  {key: 'TH', 'label':'Thailand','currencyflag':''},
  {key: 'BS', 'label':'The Bahama','currencyflag':''},
  {key: 'GM', 'label':'The Gambia','currencyflag':''},
  {key: 'TG', 'label':'Togo','currencyflag':''},
  {key: 'TK', 'label':'Tokelau','currencyflag':''},
  {key: 'TO', 'label':'Tonga','currencyflag':''},
  {key: 'TT', 'label':'Trinidad and Tobago','currencyflag':''},
  {key: 'TN', 'label':'Tunisia','currencyflag':''},
  {key: 'TR', 'label':'Turkey','currencyflag':''},
  {key: 'TM', 'label':'Turkmenistan','currencyflag':''},
  {key: 'TC', 'label':'Turks and Caicos Islands','currencyflag':''},
  {key: 'TV', 'label':'Tuvalu','currencyflag':''},
  {key: 'VI', 'label':'US Virgin Islands','currencyflag':''},
  {key: 'UG', 'label':'Uganda','currencyflag':''},
  {key: 'UA', 'label':'Ukraine','currencyflag':''},
  {key: 'AE', 'label':'United Arab Emirates','currencyflag':''},
  {key: 'UM', 'label':'United States Minor Outlying Islands','currencyflag':''},
  {key: 'UY', 'label':'Uruguay','currencyflag':''},
  {key: 'UZ', 'label':'Uzbekistan','currencyflag':''},
  {key: 'VU', 'label':'Vanuatu','currencyflag':''},
  {key: 'VA', 'label':'Vatican City','currencyflag':''},
  {key: 'VE', 'label':'Venezuela','currencyflag':''},
  {key: 'VN', 'label':'Vietnam','currencyflag':''},
  {key: 'WF', 'label':'Wallis and Futuna Islands','currencyflag':''},
  {key: 'EH', 'label':'Western Sahara','currencyflag':''},
  {key: 'YE', 'label':'Yemen','currencyflag':''},
  {key: 'ZM', 'label':'Zambia','currencyflag':''},
  {key: 'ZW', 'label':'Zimbabwe','currencyflag':''}
]
