development:
  server: "http://localhost:3000"
  developer_api_key: "26233b7b68290c7c7d4eec03643d0cf3e9b88ba8"
  user_api_key: "10dad82539189c5cd8c9b78209d98233a83ba477"
  account_id: 11 

production:
  server: "<%= ENV['RADIUM_SERVER_URL'] %>"
  developer_api_key: "<%= ENV['RADIUM_API_KEY'] %>"
  user_api_key: "<%= ENV['RADIUM_USER_API_KEY'] %>"
  account_id: "<%= ENV['RADIUM_ACCOUNT_ID'] %>"
