development:
  server: "<%= ENV['RADIUM_SERVER_URL'] || 'http://api.radiumcrm.com' %>"
  developer_api_key: "26233b7b68290c7c7d4eec03643d0cf3e9b88ba8"
  user_api_key: "d9ee8d3c34d1e165b442d269176781712e283aca"
  account_id: 4 

production:
  server: "<%= ENV['RADIUM_SERVER_URL'] %>"
  developer_api_key: "<%= ENV['RADIUM_API_KEY'] %>"
  user_api_key: "<%= ENV['RADIUM_USER_API_KEY'] %>"
  account_id: "<%= ENV['RADIUM_ACCOUNT_ID'] %>"
